steps:
  # build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/pluscode", "."]
  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/pluscode"]
  # deploy container image to GKE
##- name: "gcr.io/cloud-builders/gke-deploy"
##  args:
##  - run
##  - --filename=kubeconfig.yaml
##  - --image=gcr.io/$PROJECT_ID/pluscode
##  - --location=asia-southeast1-a
##  - --cluster=midas-test-1-kub

## for testing changes
